[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
